--------------------------------------------------------
--  파일이 생성됨 - 목요일-6월-23-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SU_BOARD_ATTACHMENT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SU_BOARD_ATTACHMENT" 
   (	"BOARD_ATTACHMENT_NO" NUMBER, 
	"BOARD_NO" NUMBER, 
	"BOARD_ATTACHMENT_ORIGINAL_FILENAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"BOARD_ATTACHMENT_RENAME_FILENAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.SU_BOARD_ATTACHMENT
SET DEFINE OFF;
Insert into ADMIN.SU_BOARD_ATTACHMENT (BOARD_ATTACHMENT_NO,BOARD_NO,BOARD_ATTACHMENT_ORIGINAL_FILENAME,BOARD_ATTACHMENT_RENAME_FILENAME) values (141,283,'분실한 에어팟 사진.jfif','20220623_005558216_586.jfif');
Insert into ADMIN.SU_BOARD_ATTACHMENT (BOARD_ATTACHMENT_NO,BOARD_NO,BOARD_ATTACHMENT_ORIGINAL_FILENAME,BOARD_ATTACHMENT_RENAME_FILENAME) values (121,259,'—Pngtree—vector male student icon_3785524.png','20220622_014939966_661.png');
--------------------------------------------------------
--  DDL for Index PK_BOARD_ATTACHMENT_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_BOARD_ATTACHMENT_NO" ON "ADMIN"."SU_BOARD_ATTACHMENT" ("BOARD_ATTACHMENT_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table SU_BOARD_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SU_BOARD_ATTACHMENT" MODIFY ("BOARD_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_BOARD_ATTACHMENT" MODIFY ("BOARD_ATTACHMENT_ORIGINAL_FILENAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_BOARD_ATTACHMENT" MODIFY ("BOARD_ATTACHMENT_RENAME_FILENAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_BOARD_ATTACHMENT" ADD CONSTRAINT "PK_BOARD_ATTACHMENT_NO" PRIMARY KEY ("BOARD_ATTACHMENT_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SU_BOARD_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SU_BOARD_ATTACHMENT" ADD CONSTRAINT "FK_BOARD_ATTACHMENT_BOARD_NO" FOREIGN KEY ("BOARD_NO")
	  REFERENCES "ADMIN"."SU_BOARD" ("BOARD_NO") ON DELETE CASCADE ENABLE;
