--------------------------------------------------------
--  파일이 생성됨 - 목요일-6월-23-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD_COMMENT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."BOARD_COMMENT" 
   (	"COMMENT_NO" NUMBER, 
	"MEMBER_ID" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTENT" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"BOARD_NO" NUMBER, 
	"REG_DATE" DATE DEFAULT sysdate
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.BOARD_COMMENT
SET DEFINE OFF;
Insert into ADMIN.BOARD_COMMENT (COMMENT_NO,MEMBER_ID,CONTENT,BOARD_NO,REG_DATE) values (81,'hongk','헉 제가 주운거랑 똑같네요 ㅠㅠ 학생회실 분실물센터에 제가 맡겨놨습니다. 가서 한번 확인해보세요..!!',283,to_date('22/06/22','RR/MM/DD'));
Insert into ADMIN.BOARD_COMMENT (COMMENT_NO,MEMBER_ID,CONTENT,BOARD_NO,REG_DATE) values (101,'admin','재학생의 경우 직전학기를 12학점 이상 이수해야하고, 백분위가 80점 이상은 성적을 획득하셔야 합니다.',104,to_date('22/06/23','RR/MM/DD'));
Insert into ADMIN.BOARD_COMMENT (COMMENT_NO,MEMBER_ID,CONTENT,BOARD_NO,REG_DATE) values (41,'honggd','비밀 ~',240,to_date('22/06/21','RR/MM/DD'));
Insert into ADMIN.BOARD_COMMENT (COMMENT_NO,MEMBER_ID,CONTENT,BOARD_NO,REG_DATE) values (102,'hongk','저용
',282,to_date('22/06/23','RR/MM/DD'));
Insert into ADMIN.BOARD_COMMENT (COMMENT_NO,MEMBER_ID,CONTENT,BOARD_NO,REG_DATE) values (63,'admin','네 은행에서 신청하시면 됩니다. :>',238,to_date('22/06/22','RR/MM/DD'));
Insert into ADMIN.BOARD_COMMENT (COMMENT_NO,MEMBER_ID,CONTENT,BOARD_NO,REG_DATE) values (62,'admin','안녕하세요
',259,to_date('22/06/21','RR/MM/DD'));
Insert into ADMIN.BOARD_COMMENT (COMMENT_NO,MEMBER_ID,CONTENT,BOARD_NO,REG_DATE) values (61,'admin','안녕하세요
',259,to_date('22/06/21','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index PK_BOARD_COMMENT_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_BOARD_COMMENT_NO" ON "ADMIN"."BOARD_COMMENT" ("COMMENT_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."BOARD_COMMENT" ADD CONSTRAINT "PK_BOARD_COMMENT_NO" PRIMARY KEY ("COMMENT_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."BOARD_COMMENT" ADD CONSTRAINT "FK_BOARD_COMMENT_MEMBER_ID" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "ADMIN"."SU_MEMBER" ("MEMBER_ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "ADMIN"."BOARD_COMMENT" ADD CONSTRAINT "FK_BOARD_COMMENT_BOARD_NO" FOREIGN KEY ("BOARD_NO")
	  REFERENCES "ADMIN"."SU_BOARD" ("BOARD_NO") ON DELETE CASCADE ENABLE;
