--------------------------------------------------------
--  파일이 생성됨 - 목요일-6월-23-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SU_DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SU_DEPARTMENT" 
   (	"DEPARTMENT_NO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DEPARTMENT_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.SU_DEPARTMENT
SET DEFINE OFF;
Insert into ADMIN.SU_DEPARTMENT (DEPARTMENT_NO,DEPARTMENT_NAME) values ('D1','컴퓨터소프트웨어학과');
Insert into ADMIN.SU_DEPARTMENT (DEPARTMENT_NO,DEPARTMENT_NAME) values ('D2','정보통신공학과');
Insert into ADMIN.SU_DEPARTMENT (DEPARTMENT_NO,DEPARTMENT_NAME) values ('D3','전자공학과');
Insert into ADMIN.SU_DEPARTMENT (DEPARTMENT_NO,DEPARTMENT_NAME) values ('D4','생활체육과');
Insert into ADMIN.SU_DEPARTMENT (DEPARTMENT_NO,DEPARTMENT_NAME) values ('D5','경영학과');
Insert into ADMIN.SU_DEPARTMENT (DEPARTMENT_NO,DEPARTMENT_NAME) values ('D0','관리자');
--------------------------------------------------------
--  DDL for Index PK_DEPARTMENT_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_DEPARTMENT_NO" ON "ADMIN"."SU_DEPARTMENT" ("DEPARTMENT_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table SU_DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SU_DEPARTMENT" MODIFY ("DEPARTMENT_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_DEPARTMENT" MODIFY ("DEPARTMENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_DEPARTMENT" ADD CONSTRAINT "PK_DEPARTMENT_NO" PRIMARY KEY ("DEPARTMENT_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
