--------------------------------------------------------
--  파일이 생성됨 - 목요일-6월-23-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SU_GRADE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SU_GRADE" 
   (	"REGISTER_NO" NUMBER, 
	"GRADE_MIDDLE" NUMBER, 
	"GRADE_FINAL" NUMBER, 
	"GRADE_ASSIGNMENT" NUMBER, 
	"GRADE_ATTEND" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.SU_GRADE
SET DEFINE OFF;
Insert into ADMIN.SU_GRADE (REGISTER_NO,GRADE_MIDDLE,GRADE_FINAL,GRADE_ASSIGNMENT,GRADE_ATTEND) values (64,10,10,10,10);
Insert into ADMIN.SU_GRADE (REGISTER_NO,GRADE_MIDDLE,GRADE_FINAL,GRADE_ASSIGNMENT,GRADE_ATTEND) values (null,9,9,9,9);
Insert into ADMIN.SU_GRADE (REGISTER_NO,GRADE_MIDDLE,GRADE_FINAL,GRADE_ASSIGNMENT,GRADE_ATTEND) values (null,30,40,20,10);
Insert into ADMIN.SU_GRADE (REGISTER_NO,GRADE_MIDDLE,GRADE_FINAL,GRADE_ASSIGNMENT,GRADE_ATTEND) values (1,25,35,20,10);
Insert into ADMIN.SU_GRADE (REGISTER_NO,GRADE_MIDDLE,GRADE_FINAL,GRADE_ASSIGNMENT,GRADE_ATTEND) values (2,25,35,15,5);
Insert into ADMIN.SU_GRADE (REGISTER_NO,GRADE_MIDDLE,GRADE_FINAL,GRADE_ASSIGNMENT,GRADE_ATTEND) values (3,20,25,20,10);
Insert into ADMIN.SU_GRADE (REGISTER_NO,GRADE_MIDDLE,GRADE_FINAL,GRADE_ASSIGNMENT,GRADE_ATTEND) values (8,30,35,10,10);
Insert into ADMIN.SU_GRADE (REGISTER_NO,GRADE_MIDDLE,GRADE_FINAL,GRADE_ASSIGNMENT,GRADE_ATTEND) values (null,20,20,10,10);
Insert into ADMIN.SU_GRADE (REGISTER_NO,GRADE_MIDDLE,GRADE_FINAL,GRADE_ASSIGNMENT,GRADE_ATTEND) values (65,10,10,10,10);
Insert into ADMIN.SU_GRADE (REGISTER_NO,GRADE_MIDDLE,GRADE_FINAL,GRADE_ASSIGNMENT,GRADE_ATTEND) values (64,10,10,10,10);
--------------------------------------------------------
--  Ref Constraints for Table SU_GRADE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SU_GRADE" ADD CONSTRAINT "FK_GRADE_REGISTER_NO" FOREIGN KEY ("REGISTER_NO")
	  REFERENCES "ADMIN"."SU_REGISTER" ("REGISTER_NO") ON DELETE SET NULL ENABLE;
