--------------------------------------------------------
--  파일이 생성됨 - 목요일-6월-23-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SU_MEMBER
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SU_MEMBER" 
   (	"MEMBER_NO" NUMBER, 
	"DEPARTMENT_NO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_ID" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_PW" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_NAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_BIRTH" DATE, 
	"MEMBER_PHONE" CHAR(11 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_EMAIL" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_IMG" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_ROLE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_LEVEL" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT '1', 
	"ENROLL_DATE" DATE DEFAULT sysdate
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.SU_MEMBER
SET DEFINE OFF;
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (162,'D1','aa1234','fZd6HdWl1fkPXj9WT4B/JmTGq7tSNvaAL4sLAUw6La3IMtLtfQUbnNsx9iQf8ANWZW6GLL4FSpwea62aq0sC1g==','김에이',to_date('94/07/07','RR/MM/DD'),'01012341234','sonsg1234@naver.con',null,'S','1',to_date('22/06/22','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (201,'D1','test12345','vm+KhAqkF+6t1M2c9xFrEP3i8fWrvKQHSbaIoGO9qto2MLemDT//xtACDZ/8Cg21IeSnylivFTeHZBHbzA5usA==','김테스트',to_date('94/07/07','RR/MM/DD'),'01012345123','test12345@naver.com',null,'S','1',to_date('22/06/23','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (144,'D1','aaaa1234','Ki/7jgkv4t5NuQg23U5ReHj4NJZYg9H17ROjEKFWYyQ8uXjhZ4ZUAf1P6nUmle7Sq8SoRpggyrtb7Z9RNKnskQ==','에이비',to_date('94/07/07','RR/MM/DD'),'01012341234','aaaa1234@naver.com',null,'S','1',to_date('22/06/22','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (101,'D3','coding1234','JW8rUPyztV5kuFZOTlI42Nd1EDZu9CTSx7P+jpdECzDFqRDuWfZ8jOou3Oex7g4ShCySaQ77jW2a5ROCX2cHGA==','김코딩',to_date('94/07/07','RR/MM/DD'),'01012341234','coding1234@naver.com',null,'S','1',to_date('22/06/20','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (7,'D3','electric01','R5UqTBv9ZCg9t7Uy3DwvbRiZD3kdqQLzFSbQ9iWqtO5hAeZY7fBn6fbs5D8KxVoqIhsmrmmKKERuyo02Is51qg==','전교수',to_date('66/06/06','RR/MM/DD'),'01012381239','electric01@gmail,com',null,'P',null,to_date('22/06/10','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (8,'D3','electric02','O8PTMpEMyiFuzD6W1w+c4+L86pggcFZ8gjVqS+4UMRvqYYBjiRFyia71RmAA+J1yb5e1gaKGBi5fpuHCVF6uMw==','장교수',to_date('55/05/05','RR/MM/DD'),'01012371235','electric012@gmail.com',null,'P',null,to_date('22/06/10','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (9,'D3','electric03','FSFl1N4WnyQdes+ce3lruWTj49qo5mGjC5hBKsbTRvT5tvp2SIo7REE8nVdLGCg+4Ht5yedVJ5w8PixAC7ZYZg==','송교수',to_date('77/07/07','RR/MM/DD'),'01012311232','electric03@gmail.com',null,'P',null,to_date('22/06/10','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (10,'D5','kimgy','J90eDV4AmUUPcg1brzAumtg7455sME4ikhsMMYy9wuG1GXzlaSOSQVDb6jnCbHB/SU0GTRA86nw1k5q2cqeXHQ==','김경영',to_date('65/12/18','RR/MM/DD'),'01098769876','kimgy@gmail.com',null,'P',null,to_date('22/06/10','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (11,'D5','leegy','HqK20e81JP08hxEU+s01P6SNCZi0vdiDuRKtf8ZHJTV4VfXMokZpsnIUefNb6kAZYGX1nvaQDSHNv3uSqvKQwg==','이경영',to_date('70/12/04','RR/MM/DD'),'01078787878','leegy@gmail.com',null,'P',null,to_date('22/06/10','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (12,'D5','parkgy','SNLwe7m/RCIjSLVT1qfi4Uqfep7rBg+svlLp8QsXJ0iaMMR0MHvuygzivhZfuiYvLyikx4mpcKBzidkX/7EGog==','박경영',to_date('59/01/23','RR/MM/DD'),'01056568787','parkgy@gmail.com',null,'P',null,to_date('22/06/10','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (4,'D1','computer1','PlomRR9tKX660v/TnFU54NwoJo6TRwCGS/JTtNDgmPexqO53ktmRNA6iGS2LGZEy6jg+RkySDQvQW66AWbkXuA==','홍창기',to_date('80/06/22','RR/MM/DD'),'01012341234','computer1@naver.com',null,'P',null,to_date('22/06/10','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (5,'D1','computer2','h7l8pynd84XLrb+sR1OGGldkH3QYbFqEUi+4VrtSqbnUwiMiJA/XwKZs8Ji6T0BzQRHGoHEcaCcbSou+X9n3uw==','이재원',to_date('90/06/22','RR/MM/DD'),'01012341234','computer2@naver.com',null,'P',null,to_date('22/06/10','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (6,'D1','computer3','az6L5BT9e+Z3zyHe+7eQ8MGQdYflD5kF1wdhjSU6AnlF6J+xk1S4dZveaETqexnibrj1r1VQMGXMLzmbtMUJlw==','오지환',to_date('70/06/22','RR/MM/DD'),'01012341234','computer3@naver.com',null,'P',null,to_date('22/06/10','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (1,'D2','codinggosu','uMUyd+DFxyuIew4EwJW6Zn7ZMmImbiK+Fz3WaccxDWKRyYTms4Nk5Ug/33IlX6E3FoTISwDKeVh8Ul5UGatyeQ==','전교수',to_date('60/05/15','RR/MM/DD'),'01012345678','gosu@naver.com',null,'P',null,to_date('22/06/10','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (2,'D2','sqlgosu','ewMU2sG7/XoCrfeh2OAJarVDmMesX5ozcsTQBAH7IgtVkP935HdSAS3qQlaJuca+lnj4JGSXCpZfVsd/RP8ipg==','김고수',to_date('59/04/13','RR/MM/DD'),'01012123434','sql@naver.com',null,'P',null,to_date('22/06/10','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (3,'D2','ajaxgosu','3bc0gUcJ1M/bs0svjPQQZWEqeGromHphZ4BndDm7/Vjd7kx2H7I7IsuXITzX9X19K3m4CEQpRz08N6tG6OinKA==','엘고수',to_date('70/03/03','RR/MM/DD'),'01012341212','ajax@naver.com',null,'P',null,to_date('22/06/10','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (13,'D4','physical','BJnT/QphubXp2bWps6vOJ/VpRzGiNQ2Nf/96HXMYsjfVVy/uRwxu/ctkh1esv+HJLOIrupvcRjDjFOEFexEyuw==','아고수',to_date('62/06/01','RR/MM/DD'),'01014235020','physical@gmail.com',null,'P',null,to_date('22/06/10','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (14,'D4','ohohs','zEOxtSHyYLpaMRuBHMg5lWv+Ki/1D7K0zvGTGBWzw2xvC9nPg/JAJavF3e6WqurEx7IuOkHayhpj0WAHdmcyIw==','한운동',to_date('56/12/25','RR/MM/DD'),'01094805536','ohohs@naver.com',null,'P',null,to_date('22/06/10','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (15,'D4','swimss','w4nuXzjjxYmR3RNcpnIRaKbamn54nLKpgiJl5j6w7cc4cnkmm6EeAYHJx7G+tLLrSVGDd/0NIteJvCHbaeAkMA==','박태환',to_date('89/09/27','RR/MM/DD'),'01089092727','park@naver.com',null,'P',null,to_date('22/06/10','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (11111111,'D1','honggd','pPQhE2dz1CciUwfgsxBAKT7P5Ji9ppMEm8jDiraEVewDeV/QbRypPSQC6YK+qNITJLl73kXlHFY4yulpV0jxzA==','홍길동',to_date('97/02/03','RR/MM/DD'),'01014781478','honggd@naver.com',null,'S','1',to_date('22/06/15','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (11111112,'D1','qwerty','dwscFdjHOBrdrPjdDgS59PgOfvTWEJs6jv/TDZI7n4BpvufqaQmm6Auu/3mNrotq1CnZC7H5Z+Lfh/GazpRRKw==','쿠어티',to_date('96/09/09','RR/MM/DD'),'01044444444','qwerty@naver.com',null,'S','2',to_date('22/06/15','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (11111113,'D1','sinsa','VhX5yA0UMyKhIu26Iuc5Zs5ApAvXd4JPjcViP9b88YcS6ZFjokpnuTH61pxeHDiAGmQZBFDTiLRcBVQ1MTlvEg==','신사임당',to_date('98/04/24','RR/MM/DD'),'01033333333','sinsa@naver.com',null,'S','3',to_date('22/06/15','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (22222221,'D4','hongk','sR8Uulu0ZBB5W3llzqzmoy487ajhBLKQI1AkAjbiOpDKsalL2We3oE9/CzCk4tSFHpqiEhRtlc0TNJA950FT3g==','홍경희',to_date('98/07/07','RR/MM/DD'),'01012347896','hongk@naver.com',null,'S','1',to_date('22/06/15','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (22222222,'D2','choik','HCriFhGggjn4NGtHtXkP9/DyQo4yvSst7l6WOVSOQvgCDV4H6qfUGywymChYcC7pzunGi/GHn7AiGbhUsuDeLw==','최경희',to_date('95/05/05','RR/MM/DD'),'01011112222','choik@naver.com',null,'S','1',to_date('22/06/15','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (22222223,'D2','jungk','IwSO2fb+En5Ps+SpdxOza4UETHVEle6mAVfAOLwSSevEuECwhDy/p4OfkKgFCrnpYeQO4lRhNaTmQDv/XAJ/Mw==','정경훈',to_date('99/08/07','RR/MM/DD'),'01022221111','jungk@naver.com',null,'S','2',to_date('22/06/15','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (0,'D0','admin','kvOffyqGmDjNUIXm8X/IIQm8+YzWKkfLw3njjegLvAITojzubkoT3myq4K3Yo5AnLW8Ig8J0Mgsf9g28/G3XUA==','관리자',to_date('11/11/11','RR/MM/DD'),'01000000000','admin@naver.com',null,'A',null,to_date('22/06/15','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (33333331,'D3','sundi','jZHnsRgFH/UJB9FvMbDczv9Bw0ZwmIv6YnRfICyX38zIXUThKSL9T1uHKbeykX0IJ5nbKAtoeThMJIXPkwRHbg==','선동일',to_date('90/02/06','RR/MM/DD'),'01099546325','sundi@naver.com',null,'S','3',to_date('22/06/15','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (33333332,'D3','songjk','stuI7wemW2e20xYP2RDoTZHImNdOoy4O4URHLoOGMM5qQ8Qt8Fr4xOxj6MVjrzlce9zM23qfGTUOlZxWlXmrYQ==','송종기',to_date('01/12/01','RR/MM/DD'),'01055567778','songjk@naver.com',null,'S','4',to_date('22/06/15','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (33333333,'D3','nohc','SmxBnYOweNQKXRw8vSu5J2bLNfeVEue9/auwa/4Kp8/R4WV8CfF6iplTZFQtifWgJ05RKkWjsyPkPGkHPJDmzA==','노옹철',to_date('00/12/06','RR/MM/DD'),'01012128989','nohc@naver.com',null,'S','1',to_date('22/06/15','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (44444441,'D4','songeh','L0XgSDQJDE2cGDaL5dl5aH8KVC4C+dd4HIu7q3jJ9pUiUpU95SlLyk2tYQIGVP2o+O70cPAmTF+sYVd7rFTb9g==','송은희',to_date('02/01/12','RR/MM/DD'),'01098980432','songe@naver.com',null,'S','2',to_date('22/06/15','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (44444442,'D4','yoogs','Ypf7Txr9Xm197mEzR3UVwuMHJsOu5Hzj/Use6ibEtNGSayd/ZVoeKPAbJOOd8vFntdyjDgkgwwiQOa3KCQiUCQ==','유관순',to_date('99/11/12','RR/MM/DD'),'01093421212','yoogs@naver.com',null,'S','3',to_date('22/06/15','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (44444443,'D4','jungjh','dgk8sH+cEQ2zKC/jEOzykgbGq0IE0vXSsHyaQYVuA3tjgrNhwD0VhnJHkj16vfz9VqrutTGpNXULtcp6V91eUg==','정중하',to_date('98/12/30','RR/MM/DD'),'01087234343','jungjh@naver.com',null,'S','4',to_date('22/06/15','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (55555551,'D5','packnr','tpmJNv4gI9SaC3SCKZjQa8W7eyvMEMR57jaEtXsEUYsHonaEsE5Y/rY4eSrjTny5viu3tPGjYPXwfQwlJdDIdg==','박나라',to_date('00/12/05','RR/MM/DD'),'01011112233','packnr@naver.com',null,'S','1',to_date('22/06/15','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (55555552,'D5','haiy','xQzrGyxH9pLWppEurRkVPsjxDCGCLLwBwsNguU9GwoKOJ5QW+11HKegcxSOd1r72k+f/RUrIQJBPMO1Yu5uo/g==','하이유',to_date('94/03/31','RR/MM/DD'),'01099996666','haiy@naver.com',null,'S','2',to_date('22/06/15','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (61,'D1','choiyj','GRG14pxnnH9v0qSQDucsockDtszK1mI+Y++H30H8u6TuN/cIu+mC2CXKSuAvVJz8JLhiAkqALKgNt2Z4d74AjQ==','최예진',to_date('96/06/23','RR/MM/DD'),'01012341234','choiyj@naver.com',null,'S','1',to_date('22/06/16','RR/MM/DD'));
Insert into ADMIN.SU_MEMBER (MEMBER_NO,DEPARTMENT_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_IMG,MEMBER_ROLE,MEMBER_LEVEL,ENROLL_DATE) values (203,'D1','test1234','GPvnm5AIJNTHvDIefgA8HcEHUx9Rgms5XqOduaQMPOd6NLCRFer/IatRz9Rp14hpCCUJV2AsJNiUvYXttpgvUQ==','김테스',to_date('94/07/07','RR/MM/DD'),'01012341234','test1234@naver.com',null,'S','1',to_date('22/06/23','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index PK_MEMBER_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_MEMBER_NO" ON "ADMIN"."SU_MEMBER" ("MEMBER_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UQ_MEMBER_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."UQ_MEMBER_ID" ON "ADMIN"."SU_MEMBER" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table SU_MEMBER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SU_MEMBER" MODIFY ("MEMBER_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_MEMBER" MODIFY ("DEPARTMENT_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_MEMBER" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_MEMBER" MODIFY ("MEMBER_PW" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_MEMBER" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_MEMBER" MODIFY ("MEMBER_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_MEMBER" MODIFY ("MEMBER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_MEMBER" MODIFY ("MEMBER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_MEMBER" MODIFY ("MEMBER_ROLE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_MEMBER" ADD CONSTRAINT "CK_MEMBER_ROLE" CHECK (member_role in ('A', 'P', 'S')) ENABLE;
  ALTER TABLE "ADMIN"."SU_MEMBER" ADD CONSTRAINT "CK_MEMBER_LEVEL" CHECK (member_level in('0','1', '2', '3', '4')) ENABLE;
  ALTER TABLE "ADMIN"."SU_MEMBER" ADD CONSTRAINT "PK_MEMBER_NO" PRIMARY KEY ("MEMBER_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "ADMIN"."SU_MEMBER" ADD CONSTRAINT "UQ_MEMBER_ID" UNIQUE ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SU_MEMBER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SU_MEMBER" ADD CONSTRAINT "FK_MEMBER_DEPARTMENT_NO" FOREIGN KEY ("DEPARTMENT_NO")
	  REFERENCES "ADMIN"."SU_DEPARTMENT" ("DEPARTMENT_NO") ON DELETE SET NULL ENABLE;
