--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-10-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SU_MEMBER
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SU_MEMBER" 
   (	"MEMBER_NO" NUMBER, 
	"DEPARTMENT_NO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_ID" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_PW" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_NAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_BIRTH" DATE, 
	"MEMBER_PHONE" CHAR(11 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_EMAIL" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_IMG" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_ROLE" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_LEVEL" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"ENROLL_DATE" DATE DEFAULT sysdate
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_MEMBER_NO" ON "ADMIN"."SU_MEMBER" ("MEMBER_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UQ_MEMBER_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."UQ_MEMBER_ID" ON "ADMIN"."SU_MEMBER" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table SU_MEMBER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SU_MEMBER" MODIFY ("MEMBER_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_MEMBER" MODIFY ("DEPARTMENT_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_MEMBER" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_MEMBER" MODIFY ("MEMBER_PW" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_MEMBER" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_MEMBER" MODIFY ("MEMBER_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_MEMBER" MODIFY ("MEMBER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_MEMBER" MODIFY ("MEMBER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_MEMBER" MODIFY ("MEMBER_ROLE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_MEMBER" ADD CONSTRAINT "CK_MEMBER_ROLE" CHECK (member_role in ('A', 'P', 'S')) ENABLE;
  ALTER TABLE "ADMIN"."SU_MEMBER" ADD CONSTRAINT "CK_MEMBER_LEVEL" CHECK (member_level in('1', '2', '3', '4')) ENABLE;
  ALTER TABLE "ADMIN"."SU_MEMBER" ADD CONSTRAINT "PK_MEMBER_NO" PRIMARY KEY ("MEMBER_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "ADMIN"."SU_MEMBER" ADD CONSTRAINT "UQ_MEMBER_ID" UNIQUE ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SU_MEMBER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SU_MEMBER" ADD CONSTRAINT "FK_MEMBER_DEPARTMENT_NO" FOREIGN KEY ("DEPARTMENT_NO")
	  REFERENCES "ADMIN"."SU_DEPARTMENT" ("DEPARTMENT_NO") ON DELETE SET NULL ENABLE;
