--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-10-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SU_NOTICE_ATTACHMENT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SU_NOTICE_ATTACHMENT" 
   (	"NOTICE_ATTACHMENT_NO" NUMBER, 
	"NOTICE_NO" NUMBER, 
	"NOTICE_ATTACHMENT_ORIGINAL_FILENAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"NOTICE_ATTACHMENT_RENAME_FILENAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_NOTICE_ATTACHMENT_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_NOTICE_ATTACHMENT_NO" ON "ADMIN"."SU_NOTICE_ATTACHMENT" ("NOTICE_ATTACHMENT_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table SU_NOTICE_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SU_NOTICE_ATTACHMENT" MODIFY ("NOTICE_ATTACHMENT_ORIGINAL_FILENAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_NOTICE_ATTACHMENT" MODIFY ("NOTICE_ATTACHMENT_RENAME_FILENAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_NOTICE_ATTACHMENT" ADD CONSTRAINT "PK_NOTICE_ATTACHMENT_NO" PRIMARY KEY ("NOTICE_ATTACHMENT_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "ADMIN"."SU_NOTICE_ATTACHMENT" MODIFY ("NOTICE_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SU_NOTICE_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SU_NOTICE_ATTACHMENT" ADD CONSTRAINT "FK_NOTICE_ATTACHMENT_NOTICE_NO" FOREIGN KEY ("NOTICE_NO")
	  REFERENCES "ADMIN"."SU_NOTICE" ("NOTICE_NO") ON DELETE CASCADE ENABLE;
