--------------------------------------------------------
--  파일이 생성됨 - 목요일-6월-23-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SU_NOTICE_ATTACHMENT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SU_NOTICE_ATTACHMENT" 
   (	"NOTICE_ATTACHMENT_NO" NUMBER, 
	"NOTICE_NO" NUMBER, 
	"NOTICE_ATTACHMENT_ORIGINAL_FILENAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"NOTICE_ATTACHMENT_RENAME_FILENAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.SU_NOTICE_ATTACHMENT
SET DEFINE OFF;
Insert into ADMIN.SU_NOTICE_ATTACHMENT (NOTICE_ATTACHMENT_NO,NOTICE_NO,NOTICE_ATTACHMENT_ORIGINAL_FILENAME,NOTICE_ATTACHMENT_RENAME_FILENAME) values (81,92,'—Pngtree—male student icon_3728055.png','20220620_093103503_128.png');
--------------------------------------------------------
--  DDL for Index PK_NOTICE_ATTACHMENT_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_NOTICE_ATTACHMENT_NO" ON "ADMIN"."SU_NOTICE_ATTACHMENT" ("NOTICE_ATTACHMENT_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table SU_NOTICE_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SU_NOTICE_ATTACHMENT" MODIFY ("NOTICE_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_NOTICE_ATTACHMENT" MODIFY ("NOTICE_ATTACHMENT_ORIGINAL_FILENAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_NOTICE_ATTACHMENT" MODIFY ("NOTICE_ATTACHMENT_RENAME_FILENAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_NOTICE_ATTACHMENT" ADD CONSTRAINT "PK_NOTICE_ATTACHMENT_NO" PRIMARY KEY ("NOTICE_ATTACHMENT_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SU_NOTICE_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SU_NOTICE_ATTACHMENT" ADD CONSTRAINT "FK_NOTICE_ATTACHMENT_NOTICE_NO" FOREIGN KEY ("NOTICE_NO")
	  REFERENCES "ADMIN"."SU_NOTICE" ("NOTICE_NO") ON DELETE CASCADE ENABLE;
