--------------------------------------------------------
--  파일이 생성됨 - 목요일-6월-23-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SU_REGISTER
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SU_REGISTER" 
   (	"REGISTER_NO" NUMBER, 
	"SUBJECT_NO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_NO" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.SU_REGISTER
SET DEFINE OFF;
Insert into ADMIN.SU_REGISTER (REGISTER_NO,SUBJECT_NO,MEMBER_NO) values (111,'D1-2202S4',11111111);
Insert into ADMIN.SU_REGISTER (REGISTER_NO,SUBJECT_NO,MEMBER_NO) values (64,'D5-2202S4',11111111);
Insert into ADMIN.SU_REGISTER (REGISTER_NO,SUBJECT_NO,MEMBER_NO) values (112,'D1-2202S2',11111111);
Insert into ADMIN.SU_REGISTER (REGISTER_NO,SUBJECT_NO,MEMBER_NO) values (114,'D3-2202S3',11111111);
Insert into ADMIN.SU_REGISTER (REGISTER_NO,SUBJECT_NO,MEMBER_NO) values (7,'D1-2201S7',11111113);
Insert into ADMIN.SU_REGISTER (REGISTER_NO,SUBJECT_NO,MEMBER_NO) values (8,'D1-2201S7',11111111);
Insert into ADMIN.SU_REGISTER (REGISTER_NO,SUBJECT_NO,MEMBER_NO) values (65,'D5-2202S4',11111112);
Insert into ADMIN.SU_REGISTER (REGISTER_NO,SUBJECT_NO,MEMBER_NO) values (113,'D3-2202S7',11111111);
Insert into ADMIN.SU_REGISTER (REGISTER_NO,SUBJECT_NO,MEMBER_NO) values (1,'D1-2201S1',11111111);
Insert into ADMIN.SU_REGISTER (REGISTER_NO,SUBJECT_NO,MEMBER_NO) values (2,'D1-2201S2',11111111);
Insert into ADMIN.SU_REGISTER (REGISTER_NO,SUBJECT_NO,MEMBER_NO) values (3,'D1-2201S3',11111111);
Insert into ADMIN.SU_REGISTER (REGISTER_NO,SUBJECT_NO,MEMBER_NO) values (4,'D1-2201S5',11111112);
Insert into ADMIN.SU_REGISTER (REGISTER_NO,SUBJECT_NO,MEMBER_NO) values (5,'D1-2201S6',11111112);
Insert into ADMIN.SU_REGISTER (REGISTER_NO,SUBJECT_NO,MEMBER_NO) values (6,'D1-2201S7',11111112);
Insert into ADMIN.SU_REGISTER (REGISTER_NO,SUBJECT_NO,MEMBER_NO) values (95,'D5-2202S1',11111111);
Insert into ADMIN.SU_REGISTER (REGISTER_NO,SUBJECT_NO,MEMBER_NO) values (9,'D1-2201S7',11111112);
Insert into ADMIN.SU_REGISTER (REGISTER_NO,SUBJECT_NO,MEMBER_NO) values (101,'D3-2202S3',11111111);
--------------------------------------------------------
--  DDL for Index PK_REGISTER_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_REGISTER_NO" ON "ADMIN"."SU_REGISTER" ("REGISTER_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table SU_REGISTER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SU_REGISTER" MODIFY ("SUBJECT_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_REGISTER" MODIFY ("MEMBER_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_REGISTER" ADD CONSTRAINT "PK_REGISTER_NO" PRIMARY KEY ("REGISTER_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SU_REGISTER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SU_REGISTER" ADD CONSTRAINT "FK_REGISTER_SUBJECT_NO" FOREIGN KEY ("SUBJECT_NO")
	  REFERENCES "ADMIN"."SU_SUBJECT" ("SUBJECT_NO") ON DELETE SET NULL ENABLE;
  ALTER TABLE "ADMIN"."SU_REGISTER" ADD CONSTRAINT "FK_REGISTER_MEMBER_NO" FOREIGN KEY ("MEMBER_NO")
	  REFERENCES "ADMIN"."SU_MEMBER" ("MEMBER_NO") ON DELETE SET NULL ENABLE;
