--------------------------------------------------------
--  파일이 생성됨 - 목요일-6월-23-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SU_SUBJECT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SU_SUBJECT" 
   (	"SUBJECT_NO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_NO" NUMBER, 
	"DEPARTMENT_NO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBJECT_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBJECT_TIME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBJECT_CLASSROOM" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBJECT_CREDIT" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBJECT_LEBEL" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBJECT_TERM" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.SU_SUBJECT
SET DEFINE OFF;
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D3-2202S1',7,'D3','전자기학','1교시~3교시','201호','3','3','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D3-2202S2',7,'D3','에너지시스템설계','1교시~3교시','202호','3','3','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D3-2202S3',7,'D3','제어시스템설계','1교시~3교시','203호','3','2','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D3-2202S4',8,'D3','로봇응용설계','1교시~3교시','204호','3','3','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D3-2202S5',8,'D3','신호및시스템','1교시~4교시','205호','3','3','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D3-2202S6',8,'D3','멀티미디어학개론','1교시~4교시','206호','3','2','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D3-2202S7',9,'D3','인공지능심화학','1교시~5교시','207호','3','3','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D3-2202S8',9,'D3','무인기시험평가이론과실제','1교시~4교시','208호','3','3','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D3-2202S9',9,'D3','드론3D매핑','1교시~5교시','209호','3','3','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D5-2202S1',10,'D5','경영학개론','1교시~3교시','302호','3','1','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D5-2202S2',10,'D5','경영정보시스템','4교시~6교시','305호','2','3','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D5-2202S3',10,'D5','생산관리','4교시~6교시','301호','3','2','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D5-2202S4',11,'D5','재무관리','1교시~3교시','302호','3','3','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D5-2202S5',11,'D5','인적자원관리','1교시~3교시','304호','3','2','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D5-2202S6',11,'D5','회계원리','4교시~6교시','302호','3','2','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D5-2202S7',12,'D5','마케팅개론','1교시~3교시','307호','2','1','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D5-2202S8',12,'D5','국제경영','4교시~6교시','309호','2','1','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D5-2202S9',12,'D5','원가관리회계','4교시~6교시','302호','3','2','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D5-2201S1',10,'D5','경영학개론','1교시~3교시','302호','3','1','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D5-2201S2',10,'D5','경영정보시스템','4교시~6교시','305호','2','3','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D5-2201S3',10,'D5','생산관리','4교시~6교시','301호','3','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D5-2201S4',11,'D5','재무관리','1교시~3교시','302호','3','3','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D5-2201S5',11,'D5','인적자원관리','1교시~3교시','304호','3','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D5-2201S6',11,'D5','회계원리','4교시~6교시','302호','3','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D5-2201S7',12,'D5','마케팅개론','1교시~3교시','307호','2','1','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D5-2201S8',12,'D5','국제경영','4교시~6교시','309호','2','1','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D5-2201S9',12,'D5','원가관리회계','4교시~6교시','302호','3','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D3-2201S1',7,'D3','미적분학','3교시~6교시','209호','3','3','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D3-2201S2',7,'D3','일반물리','3교시~6교시','208호','3','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D3-2201S3',7,'D3','전자회로','3교시~6교시','207호','3','3','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D3-2201S4',8,'D3','회로이론','3교시~6교시','206호','3','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D3-2201S5',8,'D3','마이크로프로세서','3교시~6교시','205호','3','3','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D3-2201S6',8,'D3','디지털공학실험','3교시~6교시','204호','3','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D3-2201S7',9,'D3','교류회로이론','3교시~6교시','203호','3','3','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D3-2201S8',9,'D3','확률과통계','3교시~6교시','202호','3','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D3-2201S9',9,'D3','네트워크보안','3교시~6교시','201호','3','3','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D1-2202S1',4,'D1','자바프로그래밍','4교시~6교시','601호','3','2','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D1-2202S2',4,'D1','C언어','1교시~3교시','602호','3','1','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D1-2202S3',4,'D1','C++','4교시~6교시','602호','3','2','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D1-2202S4',5,'D1','파이썬','1교시~3교시','601호','3','3','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D1-2202S5',5,'D1','C#','4교시~6교시','601호','3','2','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D1-2202S6',5,'D1','컴퓨터정보보안','4교시~6교시','601호','2','3','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D1-2202S7',6,'D1','웹개발기술','1교시~3교시','605호','3','4','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D1-2202S8',6,'D1','IOS','4교시~6교시','604호','3','4','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D1-2202S9',6,'D1','캡스톤디자인','1교시~4교시','603호','4','4','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D1-2201S1',4,'D1','컴퓨터공학기초','4교시~6교시','601호','3','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D1-2201S2',4,'D1','데이터베이스관리','1교시~3교시','602호','3','1','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D1-2201S3',4,'D1','운영체제실습','4교시~6교시','602호','3','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D1-2201S4',5,'D1','자료구조','1교시~3교시','601호','3','3','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D1-2201S5',5,'D1','DB프로그래밍','4교시~6교시','601호','3','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D1-2201S6',5,'D1','IoT시스템','4교시~6교시','601호','2','3','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D1-2201S7',6,'D1','알고리즘','1교시~3교시','605호','3','4','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D1-2201S8',6,'D1','웹프런트엔드실습','4교시~6교시','604호','3','4','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D1-2201S9',6,'D1','모바일프로그래밍','1교시~3교시','603호','3','4','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D2-2202S1',1,'D2','영상처리','1교시~3교시','708호','3','2','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D2-2202S2',1,'D2','임베디드시스템','1교시~3교시','608호','3','2','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D2-2202S3',1,'D2','모바일프로그래밍','1교시~4교시','301호','3','3','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D2-2202S4',2,'D2','IOT실습과응용','1교시~3교시','202호','3','2','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D2-2202S5',2,'D2','리눅스','1교시~4교시','405호','3','3','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D2-2202S6',2,'D2','대학물리학','1교시~3교시','807호','3','1','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D2-2202S7',3,'D2','디지털시스템설계','1교시~3교시','707호','3','2','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D2-2202S8',3,'D2','아두이노','1교시~4교시','403호','3','3','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D2-2202S9',3,'D2','정보통신개론','1교시~3교시','101호','3','2','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D2-2201S1',1,'D2','이동통신','1교시~2교시','201호','1','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D2-2201S2',1,'D2','선형대수학','1교시~3교시','307호','3','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D2-2201S3',1,'D2','데이터구조','4교시~6교시','505호','3','1','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D2-2201S4',2,'D2','기초전자','2교시~5교시','404호','3','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D2-2201S5',2,'D2','컴퓨팅사고와코딩기초','1교시~3교시','809호','3','1','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D2-2201S6',2,'D2','논리회로','4교시~6교시','307호','3','3','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D2-2201S7',3,'D2','대학물리학','4교시~6교시','208호','3','3','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D2-2201S8',3,'D2','종합설계','4교시~6교시','103호','3','3','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D2-2201S9',3,'D2','프로그래밍설계','1교시~3교시','203호','3','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D4-2201S1',13,'D4','트레이닝방법론','1교시~3교시','501호','3','3','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D4-2201S2',13,'D4','스포츠사회학','4교시~6교시','501호','3','3','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D4-2201S3',13,'D4','현대생활과스포츠','1교시~3교시','502호','3','4','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D4-2201S4',14,'D4','배드민턴','1교시~3교시','503호','2','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D4-2201S5',14,'D4','탁구','4교시~6교시','502호','2','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D4-2201S6',14,'D4','유아체육','1교시~3교시','504호','3','3','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D4-2201S7',15,'D4','수영','1교시~3교시','505호','2','4','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D4-2201S8',15,'D4','댄스스포츠','4교시~6교시','505호','2','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D4-2201S9',15,'D4','유도','1교시~3교시','506호','3','2','2022년도 1학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D4-2202S1',13,'D4','댄스스포츠','1교시~3교시','501호','3','3','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D4-2202S2',13,'D4','육상','4교시~6교시','501호','3','3','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D4-2202S3',13,'D4','윈드서핑','1교시~3교시','502호','3','4','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D4-2202S4',14,'D4','태권도','1교시~3교시','503호','2','2','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D4-2202S5',14,'D4','운동생리학','4교시~6교시','502호','2','2','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D4-2202S6',14,'D4','실버체육','1교시~3교시','504호','3','3','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D4-2202S7',15,'D4','교육학개론','1교시~3교시','505호','2','4','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D4-2202S8',15,'D4','구급 및 안전관리','4교시~6교시','505호','2','2','2022년도 2학기');
Insert into ADMIN.SU_SUBJECT (SUBJECT_NO,MEMBER_NO,DEPARTMENT_NO,SUBJECT_NAME,SUBJECT_TIME,SUBJECT_CLASSROOM,SUBJECT_CREDIT,SUBJECT_LEBEL,SUBJECT_TERM) values ('D4-2202S9',15,'D4','실기교육방법론','1교시~3교시','506호','3','2','2022년도 2학기');
--------------------------------------------------------
--  DDL for Index PK_SUBJECT_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_SUBJECT_NO" ON "ADMIN"."SU_SUBJECT" ("SUBJECT_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table SU_SUBJECT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SU_SUBJECT" MODIFY ("SUBJECT_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_SUBJECT" MODIFY ("MEMBER_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_SUBJECT" MODIFY ("DEPARTMENT_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_SUBJECT" ADD CONSTRAINT "PK_SUBJECT_NO" PRIMARY KEY ("SUBJECT_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SU_SUBJECT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SU_SUBJECT" ADD CONSTRAINT "FK_SUBJECT_DEPARTMENT_NO" FOREIGN KEY ("DEPARTMENT_NO")
	  REFERENCES "ADMIN"."SU_DEPARTMENT" ("DEPARTMENT_NO") ON DELETE SET NULL ENABLE;
  ALTER TABLE "ADMIN"."SU_SUBJECT" ADD CONSTRAINT "FK_SUBJECT_MEMBER_NO" FOREIGN KEY ("MEMBER_NO")
	  REFERENCES "ADMIN"."SU_MEMBER" ("MEMBER_NO") ON DELETE SET NULL ENABLE;
