--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-10-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SU_SUBJECT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SU_SUBJECT" 
   (	"SUBJECT_NO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MEMBER_NO" NUMBER, 
	"DEPARTMENT_NO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBJECT_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBJECT_TIME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBJECT_CLASSROOM" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBJECT_CREDIT" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBJECT_LEBEL" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBJECT_TERM" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_SUBJECT_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_SUBJECT_NO" ON "ADMIN"."SU_SUBJECT" ("SUBJECT_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table SU_SUBJECT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SU_SUBJECT" MODIFY ("SUBJECT_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_SUBJECT" MODIFY ("MEMBER_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_SUBJECT" MODIFY ("DEPARTMENT_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SU_SUBJECT" ADD CONSTRAINT "PK_SUBJECT_NO" PRIMARY KEY ("SUBJECT_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SU_SUBJECT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SU_SUBJECT" ADD CONSTRAINT "FK_SUBJECT_MEMBER_NO" FOREIGN KEY ("MEMBER_NO")
	  REFERENCES "ADMIN"."SU_MEMBER" ("MEMBER_NO") ON DELETE SET NULL ENABLE;
  ALTER TABLE "ADMIN"."SU_SUBJECT" ADD CONSTRAINT "FK_SUBJECT_DEPARTMENT_NO" FOREIGN KEY ("DEPARTMENT_NO")
	  REFERENCES "ADMIN"."SU_DEPARTMENT" ("DEPARTMENT_NO") ON DELETE SET NULL ENABLE;
